name: Theme preview
on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]
    branches:
      - master
    paths:
      - "themes/index.js"

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  previewTheme:
    name: Install & Preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup Node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - uses: bahmutov/npm-install@c5482d70ec8706408996e31ac94075030694993f # v1.8.32
        with:
          useLockFile: false

      - run: npm run preview-theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
